[server]
fileWatcherType = "none"
# This completely disables file watching to avoid inotify limits

[client]
toolbarMode = "minimal"

[global]
# Also suppress some warnings
showWarningOnDirectExecution = false
